class DisclaimerManager:
    """
    Manages legal disclaimers to ensure compliance with Financial Instruments and Exchange Act (FIEA).
    Mandatory injection of these disclaimers helps avoid classification as 'Investment Advice'.
    """

    DISCLAIMER_JP = """
---
**【免責事項】**
本レポートは情報提供のみを目的としており、特定の金融商品の売買を推奨・勧誘するものではありません。
本レポートに含まれる分析や予測はAIによって生成されたものであり、その正確性や完全性を保証するものではありません。
投資に関する最終的な決定は、ご自身の判断と責任において行ってください。本レポートの利用により生じたいかなる損害についても、運営者は一切の責任を負いません。
"""

    DISCLAIMER_EN = """
---
**[Disclaimer]**
This report is for informational purposes only and does not constitute investment advice or a solicitation to buy or sell any financial products.
The analysis and projections contained herein are generated by AI and no guarantee is made regarding their accuracy or completeness.
Please make final investment decisions at your own discretion and responsibility. The operator assumes no liability for any damages arising from the use of this report.
"""

    @classmethod
    def get_disclaimer(cls, lang: str = "jp") -> str:
        if lang.lower() == "en":
            return cls.DISCLAIMER_EN
        return cls.DISCLAIMER_JP

    @classmethod
    def inject(cls, content: str, lang: str = "jp") -> str:
        """Injects the mandatory disclaimer at the end of the content."""
        return content + "\n" + cls.get_disclaimer(lang)
