-- Supabase Table Definitions for Ayato Intelligence Engine

-- 1. Raw Items Table (Main persistence for RSS/intelligence hits)
CREATE TABLE IF NOT EXISTS raw_items (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    title TEXT,
    summary TEXT,
    url TEXT UNIQUE,
    published_at TIMESTAMPTZ,
    fetched_at TIMESTAMPTZ DEFAULT NOW(),
    market TEXT DEFAULT 'general',
    category TEXT DEFAULT 'News',
    raw_metadata JSONB,
    posted_x BOOLEAN DEFAULT FALSE,
    posted_bluesky BOOLEAN DEFAULT FALSE,
    posted_hatena BOOLEAN DEFAULT FALSE
);

-- 2. AI Scores Table (Link to raw_items)
CREATE TABLE IF NOT EXISTS ai_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT REFERENCES raw_items(id) ON DELETE CASCADE,
    model_name TEXT,
    score INTEGER,
    reason TEXT,
    prompt_used TEXT,
    raw_response JSONB,
    scored_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Generated Reports Table (Final output tracking)
CREATE TABLE IF NOT EXISTS generated_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT REFERENCES raw_items(id) ON DELETE CASCADE,
    title TEXT,
    content_md TEXT,
    category TEXT,
    market TEXT DEFAULT 'general',
    language TEXT DEFAULT 'jp',
    model_name TEXT,
    generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. SNS Post Logs (Optional table for quality auditing)
CREATE TABLE IF NOT EXISTS sns_post_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    platform TEXT,
    content TEXT,
    item_id TEXT,
    model TEXT,
    status TEXT
);

-- 5. Affiliates Table (Monetization management)
CREATE TABLE IF NOT EXISTS affiliates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    market TEXT DEFAULT 'any',
    header TEXT,
    description TEXT,
    cta_text TEXT,
    tracking_url TEXT,
    thumbnail_url TEXT,
    image_url TEXT,
    keywords TEXT,
    weight INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_raw_items_fetched_at ON raw_items(fetched_at DESC);
CREATE INDEX IF NOT EXISTS idx_raw_items_source ON raw_items(source);
CREATE INDEX IF NOT EXISTS idx_ai_scores_item_id ON ai_scores(item_id);
CREATE INDEX IF NOT EXISTS idx_ai_scores_score ON ai_scores(score DESC);
CREATE INDEX IF NOT EXISTS idx_generated_reports_generated_at ON generated_reports(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_sns_post_logs_item_id ON sns_post_logs(item_id);
