import logging
import re

from config import settings

logger = logging.getLogger(__name__)


class ComplianceValidator:
    """
    金融商品取引法(FIEA)等の規制に抵触しないよう、生成されたコンテンツを検証・補正するクラス。
    「投資助言」とみなされるリスクを低減するためのガードレールとして機能する。
    """

    def __init__(self):
        self.prohibited_keywords = getattr(settings, "COMPLIANCE_KEYWORDS", [])
        # 単語の境界を意識した正規表現(大文字小文字を区別しない)
        self.patterns = [
            (
                re.compile(rf"\b{re.escape(kw)}\b", re.IGNORECASE)
                if kw.isascii()
                else re.compile(re.escape(kw))
            )
            for kw in self.prohibited_keywords
        ]

    def validate(self, text: str) -> tuple[bool, list[str]]:
        """
        テキスト内に禁止ワードが含まれているかチェックする。

        Returns:
            (is_safe, found_keywords)
        """
        found = []
        for i, pattern in enumerate(self.patterns):
            if pattern.search(text):
                found.append(self.prohibited_keywords[i])

        is_safe = len(found) == 0
        if not is_safe:
            logger.warning(f"Compliance Violation Detected: Found keywords {found}")

        return is_safe, found

    def sanitize(self, text: str) -> str:
        """
        禁止ワードをマイルドに除去・置換する。
        文脈を壊しにくいよう、プレフィックスの除去を優先する。
        """
        sanitized_text = text
        for kw in self.prohibited_keywords:
            # 1. 「機密:」「Official:」などのプレフィックス形式を優先的に除去(文脈への影響が最小限)
            prefix_pattern = rf"[\*#\s]*{re.escape(kw)}[::\s]+"
            sanitized_text = re.sub(prefix_pattern, "", sanitized_text, flags=re.IGNORECASE)

            # 2. 文中の単語置換(伏せ字よりも空白やマイルドな表現に)
            if kw.isascii():
                sanitized_text = re.sub(
                    rf"\b{re.escape(kw)}\b",
                    "[NOTE]",
                    sanitized_text,
                    flags=re.IGNORECASE,
                )
            else:
                # 日本語などは [REDACTED] を避けて空文字またはマイルドな表現に
                sanitized_text = sanitized_text.replace(kw, "")

        return sanitized_text

    @staticmethod
    def inject_compliance_header(markdown_content: str) -> str:
        """
        コンプライアンス遵守のための注釈を強制的に挿入する。
        """
        notice = (
            "\n> [!NOTICE]\n"
            "> **Compliance Note**: This report is generated by a factual analysis AI tool. "
            "It is designed to extract and summarize publicly available data and does not provide "
            "financial advice, investment solicitation, or price predictions.\n"
        )
        return notice + markdown_content
